name: Deploy process
on: 
    - push
    - workflow_dispatch
jobs: 
    test: 
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            #   run: |
            #     echo "cloning repo"
            #     echo "${{toJson(github)}}"
            #     git clone https://github.com/${{github.repository}}.git
            - name: Install nodeJs
              uses: actions/setup-node@v4
              with: 
                node-version: 20

            - name: print node version
              uses: node -v

            - name: Install Dependencies
              run: npm ci
              
            - name: Run Test
              run: npm run test 

